TWEAK_NAME = AriaPrysm

AriaPrysm_FILES = AriaPrysm.m ../../Views/AriaBlurView.m ../../Views/AriaGradientView.m
AriaPrysm_CFLAGS = -fobjc-arc
AriaPrysm_LIBRARIES = gcuniversal

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk