BUNDLE_NAME = AriaPrefs

AriaPrefs_FILES = Controllers/AriaRootVC.m Cells/AriaCustomButtonCell.m ../Managers/AriaImageManager.m ../Managers/MyClass.m
AriaPrefs_CFLAGS = -fobjc-arc
AriaPrefs_LIBRARIES = gcuniversal
AriaPrefs_FRAMEWORKS = UIKit
AriaPrefs_PRIVATE_FRAMEWORKS = Preferences
AriaPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
