TWEAK_NAME = Aria

Aria_FILES = Aria.xm
Aria_CFLAGS = -fobjc-arc
Aria_LIBRARIES = gcuniversal

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
include $(THEOS_MAKE_PATH)/aggregate.mk