TWEAK_NAME = AriaStock

AriaStock_FILES = AriaStock.xm ../../Managers/AriaImageManager.m ../../Managers/RootWindow.m ../../Views/AriaBlurView.m ../../Views/AriaGradientView.m
AriaStock_CFLAGS = -fobjc-arc
AriaStock_LIBRARIES = gcuniversal

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk